### PR TITLE
🎨 fix(ui): fixes to --start --enable and --quiet flags

### LINKED ISSUE #335: --quiet results in enable/disable being skipped
The start and stop commands both have a `--quiet` flag.

This flag prevents the UI from outputting anything on start/stop, but also prevents the enable/disable step from happening.

I am not sure what the intention of the `--quiet` flag is. It only appears in a handful of places, was it a precursor to `--no-prompt`? 

@acburdine if you can clarify the intention here, I think I can fix/remove this. It's totally non-urgent except in that I am going to be removing the quiet flag when passed to `stop` from `uninstall` so that the systemd disable command is run on `uninstall`.

### PR DESCRIPTION
**Pull request by ErisDS**
refs #313

This removes the prompt for enabling as described in #313 and also deals with the slightly weird start command, as mentioned in https://github.com/TryGhost/Ghost-CLI/pull/246

- the `ghost setup --start` flag
  - The default value for "start" is "prompt"
  - The fallback default value for "start", if it's not allowed to prompt is true
  - Passing --no-start will set start to false, and not prompt
  - Passing --start will set start to true, and not prompt

- the `ghost start --enable` flag
  - Enabling doesn't trigger any prompt
  - The default value for "enable" is true
  - Passing --enable doesn't change anything
  - Passing --no-enable prevents enabling

- calling `ghost uninstall` will now call `ghost stop --disable`

----

This caused a bug with `stopping ghost` outputting multiple times

closes #335

- implement --quiet inside of ui.run

Note: even with this fix, `Starting Ghost` can output multiple times, I think because the promise for processInstance.enabled() can resolve early, and trip up the spinner logic? Not sure....

### CODE REVIEW

File: lib/commands/setup.js [hunk 1]
```diff
@@ -147,7 +147,15 @@ class SetupCommand extends Command {
...
-                if (!argv.prompt || argv.start) {
+                // If we are not allowed to prompt, set the default value, which should be true
+                if (!argv.prompt) {
+                    argv.start = true;
+                }
+
+                // If argv.start has a value, this means either --start or --no-start were explicitly provided
+                // (or --no-prompt was provided, and we already defaulted to true)
+                // In this case, we don't prompt, we use the value of argv.start
+                if (argv.start) {
```
Comment (acburdine) [inline lib/commands/setup.js]: if `--no-start` is explicitly provided, `argv.start` will still be false, and this if statement wouldn't execute.

**Comment by acburdine** [comment]
Ah I see why travis is failing on push - the branch got removed 😛

File: lib/commands/setup.js (hunk 1 above)
Comment (ErisDS) [inline lib/commands/setup.js]: Good point, I thought I'd tested all the cases but I guess I missed that one!
