### PR TITLE
fix(url): ensure trailing slash gets appended to url

### LINKED ISSUE #748: Admin interface location incorrect
### Summary

When running ghost, if a subdirectory is configured but no explicit admin url is configured the CLI outputs the admin's location incorrectly.

### Steps to Reproduce (for a bug report)

1. Create a local install (`ghost install local`)
2. Configure the url to be a subdirectory (`config set url http://localhost:2369/test` - change depending on the port that the CLI gave you)
3. Start ghost (`ghost start`)

Ghost-CLI will now output info about the Ghost install:

```
❯ ghost start
Found a development config but not a production config, running in development mode instead
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Starting Ghost
You can access your publication at http://localhost:2369/test
Your admin interface is located at http://localhost:2369/ghost/
```

The admin URL here should be http://localhost:2369/test/ghost/

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: macOS High Sierra
* Node Version: 8.10.0
* Ghost-CLI Version: 1.8.1
* Environment: development / local

### PR DESCRIPTION
**Pull request by vikaspotluri123**
closes #748 

The root of the problem stems from the fact we don't ensure trailing slashes when we set the URL. It's well-known that Ghost redirects URLs w/o a trailing slash to the trailing slash equivalent, so we might as well add the trailing slash here

Something that I would like to do but I'm not sure how to go about doing is add the trailing slash for existing installations. I know I can add a migration, but we also need to expect the URL will not be correct since it can be modified by running `ghost config set url https://my.site/blog`

### CODE REVIEW

**Comment by acburdine** [comment]
@vikaspotluri123 I was thinking we'd just fake the trailing slash when we build the admin url - would be a lot simpler.

**Comment by vikaspotluri123** [comment]
Alright, that's fine 😄 Do we _have_ to use the url module in this case? We could just as easily just do `adminUrl += 'ghost/'` and it would do the same thing, with the added benefit of being more readable - if `url.resolve`'s second argument start's with a preceding `/`, it's considered an absolute path and the path from the first argument is removed

**Comment by acburdine** [comment]
yeah - that would be fine too :)

**Comment by vikaspotluri123** [comment]
Done! 👍

File: lib/commands/start.js [hunk 1]
```diff
@@ -64,7 +63,8 @@ class StartCommand extends Command {
                         const isInstall = process.argv[2] === 'install';
                         let adminUrl = instance.config.get('admin.url') || instance.config.get('url');
 
-                        adminUrl = url.resolve(adminUrl, '/ghost/');
+                        // Strip the trailing slash and add the admin path
+                        adminUrl = adminUrl.replace(/\/$/,'') + '/ghost/';
```
Comment (acburdine) [inline lib/commands/start.js]: just to keep things consistent - can this be a template string?

Comment (vikaspotluri123) [reply lib/commands/start.js]: Yep, done 😃

**Comment by vikaspotluri123** [comment]
Nope, I just forgot to get rid of it!
