### PR TITLE
[Enhancement] Delete bootstrap-socket once ghost is stopped

### LINKED ISSUE #805: Remove bootstrap socket config after Ghost was started
### Summary

With CLI 1.9 we have invented a new mechanism for systemd to figure out if Ghost is running or not.

CLI writes into the blog's config file, but doesn't clean up it afterwards (`bootstrap-socket` options)

If you then run `ghost run` the bootstrap socket options still exist and Ghost tries to connect to the socket. That is all fine, Ghost is just trying and stops after 3 tries, but it's very confusing.

If we remove the config, the CLI will add it next time ghost get's started/restarted.

### Steps to Reproduce

1. Install Ghost on production using systemd
2. Start your blog
3. Stop your blog
4. run `ghost run`

Ghost-CLI: master

### PR DESCRIPTION
**Pull request by TonnyORG**
Expecting to fix #805, @kirrg001 please provide any feedback. I also thought in adding this line inside a `.then()` once the `systemctl stop ${this.systemdName}` had run, what do you think?

### CODE REVIEW

File: extensions/systemd/systemd.js [hunk 1]
```diff
@@ -47,6 +47,8 @@ class SystemdProcessManager extends ProcessManager {
     stop() {
         this._precheck();
 
+        this.instance.config.set('bootstrap-socket', null);
```
Comment (vikaspotluri123) [inline extensions/systemd/systemd.js]: This won't persist changes, you need to run the `save` method as well 😄

Comment (TonnyORG) [reply extensions/systemd/systemd.js]: good catch, ty for your input. I feel like I should "delete" it once the promise for the `systemctrl stop` command has been resolved, what do you think?

```
        return this.ui.sudo(`systemctl stop ${this.systemdName}`)
            .then((response) => {
                this.instance.config.set('bootstrap-socket', null);
                return this.instance.config.save();
            })
            .catch((error) => {
                throw new ProcessError(error);
            });
```

Comment (vikaspotluri123) [reply extensions/systemd/systemd.js]: In terms of when the changes to the config should be reverted, I think it would be better to do this when the [socket](https://github.com/TryGhost/Ghost-CLI/blob/1d5dab17c23541eecfd5285c2da73a48fe4380e4/lib/utils/port-polling.js) is destroyed, because it's part of the cleanup and can help mitigate issues arising from `ghost stop` not being called. However, this might be a more relevant implementation for #787

Comment (acburdine) [reply extensions/systemd/systemd.js]: I agree with @vikaspotluri123 here - the original idea for #805 was to clean it up after ghost was started, which would mean adding this line in an extra `then` block [here](https://github.com/TryGhost/Ghost-CLI/blob/478277f641ff264ed23e53d3962ab9b14be5a1db/extensions/systemd/systemd.js#L37) and [here](https://github.com/TryGhost/Ghost-CLI/blob/478277f641ff264ed23e53d3962ab9b14be5a1db/extensions/systemd/systemd.js#L72).

Also, `config.set()` returns the config instance, so you can just use `config.set('bootstrap-socket', null).save();` 😄

Comment (TonnyORG) [reply extensions/systemd/systemd.js]: @acburdine ty for your input as well, I've refactorized the code to clean it up after ghost was started (start and restart commands). I kept the original `this.instance.config` call to make it consistent with the other portions where config is called in the file.
