### PR TITLE
fix(doctor): Folder permissions check considers setuid, setgid, and sticky bits

### LINKED ISSUE #724: Ghost-CLI failing on: Checking folder permissions
This issue is a bug report.

### Summary

While following the [Install & Setup (production) tutorial](https://docs.ghost.org/v1/docs/install), the installation fails at:  Checking folder permissions

### Steps to Reproduce (for a bug report)

Follow the instructions for the Install & Setup (production) tutorial.

I follow the steps in the Installing on Linux tutorial and fail at `ghost install`, `ghost setup`, and `ghost doctor` at the exact same point: when `Checking folder permissions`. I receive a very uninformative (maybe give details about which user needs what access to where) message that states:

```
One or more errors occurred.

1) Checking folder permissions
``` 

Then it proceeds to list out each and every file/folder inside of the following folders:

- content
- versions
- system

Here's my `ls -al` output just to verify everything has the right permissions (at least based on the tutorial):

```
snarlynarwhal@halfhuman:/var/www/dwerve.com/html/ghost$ ls -al
total 28
drwxrwsr-x 5 snarlynarwhal snarlynarwhal 4096 May 17 22:20 .
drwxrwsr-x 3 www           www           4096 May 17 22:17 ..
-rw-rw-r-- 1 snarlynarwhal snarlynarwhal  517 May 17 22:20 config.production.json
drwxrwsr-x 8 ghost         ghost         4096 May 17 22:18 content
lrwxrwxrwx 1 snarlynarwhal snarlynarwhal   46 May 17 22:18 current -> /var/www/dwerve.com/html/ghost/versions/1.22.8
-rw-rw-r-- 1 snarlynarwhal snarlynarwhal   88 May 17 22:19 .ghost-cli
drwxrwsr-x 3 snarlynarwhal snarlynarwhal 4096 May 17 22:20 system
drwxrwsr-x 3 snarlynarwhal snarlynarwhal 4096 May 17 22:18 versions
snarlynarwhal@halfhuman:/var/www/dwerve.com/html/ghost$
```

### Log file (for a bug report)

```
✔ Checking system Node.js version
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
Running sudo command: systemctl is-active ghost_blog-dwerve-com
✔ Validating config
✖ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
One or more errors occurred.

1) Checking folder permissions

Message: Your installation folder contains some directories or files with incorrect permissions:
- ./
- ./content
- ./content/images
- ./content/data
...
- ./versions/1.22.8/content/settings
- ./system
- ./system/files
Run sudo find ./ -type d -exec chmod 775 {} \; and try again.

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.2
    Ghost-CLI Version: 1.7.3
    Environment: production
    Command: 'ghost update'

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

### Technical details (for a bug report)

The exact recommended stack.

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [X] Tried to find help in the forum & docs
- [X] Checked for existing issues
- [X] Attached log file
- [X] Provided technical details incl. operating system

### PR DESCRIPTION
**Pull request by snarlynarwhal**
fix(doctor): Folder permissions check considers setuid, setgid, and sticky bits

closes #724
- Prefixed the folder permissions check help command chmod parameter with "00" to clear the setuid, setgid, and sticky bits
- Updated the unit tests for folder permissions to coincide with aforementioned change

### CODE REVIEW

File: lib/commands/doctor/checks/check-permissions.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ module.exports = function checkPermissions(type, task) {
         },
         folder: {
             command: 'find ./ -type d ! -perm 775 ! -perm 755',
-            help: `Run ${chalk.green('sudo find ./ -type d -exec chmod 775 {} \\;')} and try again.`
+            help: `Run ${chalk.green('sudo find ./ -type d -exec chmod 00775 {} \\;')} and try again.`
```
Comment (vikaspotluri123) [inline lib/commands/doctor/checks/check-permissions.js]: Could you add the following comment before this line?

```js
// chmod mode from http://man7.org/linux/man-pages/man1/chmod.1.html#SETUID_AND_SETGID_BITS
```

**Comment by vikaspotluri123** [comment]
I'm thinking about if we need to add the leading zeros to the files help command as well. According to the [manual](http://man7.org/linux/man-pages/man1/chmod.1.html#SETUID_AND_SETGID_BITS), the sticky bit is cleared if the user executing the command isn't the owner or isn't in the group (of course T+C apply). Given that and the fact the user shouldn't be the owner (because Ghost should own the content folder), it seems like the owner check + the chmod command should cause the system to fix it 🤔

**Comment by snarlynarwhal** [comment]
I played around with it a bit the other day and special permissions on files did not seem to affect the installation - probably because the system fixed it as you said.
