### PR TITLE
Various SSL setup fixes

### LINKED ISSUE #302: Error when running `ghost setup ssl` twice.
Run `ghost setup ssl`. Wait that ssl setup was successful.
Run `ghost setup ssl` again. You will get an error:

```
Stack: TypeError: ctx.ssl.http._add is not a function
    at Promise.fromCallback.then (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/extensions/nginx/index.js:154:38)
    at tryCatcher (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:638:18)
    at /usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/nodeback.js:42:21
    at /usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/nginx-conf/src/conf.js:295:15
    at NginxParser.parse (/usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/nginx-conf/src/parser.js:35:14)
    at /usr/local/nvm/versions/node/v6.10.3/lib/node_modules/ghost-cli/node_modules/nginx-conf/src/parser.js:206:10
```

Workaround is:
```
rm -rf ~/.acme/your-domain`
rm -rf system/files/your-domain.conf
ghost setup nginx ssl
```

### LINKED ISSUE #309: SSL certificate generation fails due to renewal, but CLI thinks everything is okay and continues
I ran into the following situation.

I was prompted for ssl certificate generation and hitted "yes"

```
? Enter your email (used for SSL certificate generation) kate@ghost.org
Running sudo command: service nginx restart
Certificate not due for renewal yet, skipping
? Ghost-CLI would like to generate a ssl parameters file. Yes, write config file
```

But a warning popped up **Certificate not due for renewal yet, skipping**.
The CLI continued with trying to generate the certificate and then it prompted me for ssl parameter file generation, i hitted yes (i knew this is going to fail).

Then i ran into:

> Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
✖ Setting up ssl
A ProcessError occured.
Error occurred running command: '/bin/sh -c sudo service nginx restart'

I had to manually delete the ssl setup from my nginx config and restart Ghost.
This was caused by a rate limit from Letsencrypt.

What's weird here is that the CLI continues trying to generate my ssl certificate and then it prompts me for ssl parameter generation, but the ssl certificate was never created.

### PR DESCRIPTION
**Pull request by acburdine**
closes #309
- if a user deletes their instance and recreates it with the same domain, then acme will fail to generate the certificate because it already exists & is not due for renewal. We work around this issue by looking for the error and copying the right keys if it already exists

closes #302 
- checks if ssl has already been setup, if it has then skips
- better cleanup/handling of well-known config block

### CODE REVIEW

File: extensions/nginx/letsencrypt.js [hunk 1]
```diff
@@ -43,10 +44,21 @@ module.exports = function letsencrypt(instance, email, staging, renew) {
 
         // This is an execa error
         if (error.stdout.match(/Skip/)) {
-            instance.ui.log('Certificate not due for renewal yet, skipping', 'yellow');
-            return;
+            // Certificate already exists
+            if (renew) {
+                instance.ui.log('Certificate not due for renewal yet, skipping', 'yellow');
```
Comment (ErisDS) [inline extensions/nginx/letsencrypt.js]: Can do this as a direct-to-master commit - I would like this to be "SSL certificate" to be consistent 😁

Comment (acburdine) [inline extensions/nginx/letsencrypt.js]: I can add it to the PR - this still needs to be tested on Ubuntu.

**Comment by acburdine** [comment]
Have tested, these changes work 👍
