### PR TITLE
fix(run): make command descriptions clearer

### LINKED ISSUE #185: Clearer explanation for `ghost start` vs `ghost run`
```
    restart                         Restart the Ghost instance
    run                             start a managed ghost process
    service <command> [args...]     run a service-defined command
    setup [options]                 setup an installation of Ghost (after it is installed)
    start                           starts an instance of Ghost
    stop [options]                  stops a named instance of Ghost
```

The difference between run and start isn't very clear. Although `start`/`stop`/`restart` follows the normal pattern, so it's reasonably obvious which one I should use, but I almost think `run` doesn't need help output?

Surely the only people who ever need `run` are people developing process managers?

### PR DESCRIPTION
**Pull request by acburdine**
closes #185
- fix command descriptions
- output help note on `ghost run` if it is being run directly

### CODE REVIEW

File: lib/commands/run.js [hunk 1]
```diff
@@ -10,6 +10,13 @@ let instance;
 module.exports.execute = function execute() {
     checkValidInstall('run');
 
+    // If the user is running this command directly, output a little note
+    // telling them they're likely looking for `ghost start`
+    if (process.stdin.isTTY) {
+        this.ui.log('The `ghost run` command is used by the configured Ghost process manager and for debugging. ' +
```
Comment (acburdine) [inline lib/commands/run.js]: /cc @ErisDS does this message make more sense?

Comment (ErisDS) [inline lib/commands/run.js]: 👍
